version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    container_name: chalkstone-postgres
    environment:
      - POSTGRES_USER=chalkstone
      - POSTGRES_PASSWORD=chalkstone_password
      - POSTGRES_DB=chalkstone
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chalkstone"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - chalkstone-network

  # MinIO Object Storage
  minio:
    image: quay.io/minio/minio:latest
    container_name: chalkstone-minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9090"
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9090:9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - chalkstone-network

  # Create MinIO bucket on startup
  minio-setup:
    image: minio/mc:latest
    container_name: chalkstone-minio-setup
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/issues-bucket;
      /usr/bin/mc anonymous set public myminio/issues-bucket;
      exit 0;
      "
    networks:
      - chalkstone-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chalkstone-backend
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=chalkstone
      - DB_PASSWORD=chalkstone_password
      - DB_NAME=chalkstone
      - JWT_SECRET=your_jwt_secret_should_be_very_long_and_secure_in_production
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=issues-bucket
      - GIN_MODE=release
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      minio-setup:
        condition: service_completed_successfully
    networks:
      - chalkstone-network

  # Frontend Web Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chalkstone-frontend
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - chalkstone-network

networks:
  chalkstone-network:
    driver: bridge

volumes:
  postgres_data:
  minio_data: